import type { Ingredient, Recipe } from "./types";

// Datos semilla locales. Se reemplazarán por consultas a Supabase
// (tablas: recipes, recipe_ingredients, ingredients, ingredient_safety).

export const INGREDIENTS: Ingredient[] = [
  { id: "ing-pollo", name: "Pollo", category: "proteina", safety: "seguro" },
  { id: "ing-pavo", name: "Pavo", category: "proteina", safety: "seguro" },
  { id: "ing-salmon", name: "Salmón", category: "proteina", safety: "seguro", note: "Siempre bien cocido" },
  { id: "ing-huevo", name: "Huevo", category: "proteina", safety: "seguro" },
  { id: "ing-arroz", name: "Arroz", category: "cereal", safety: "seguro" },
  { id: "ing-avena", name: "Avena", category: "cereal", safety: "seguro" },
  { id: "ing-zanahoria", name: "Zanahoria", category: "vegetal", safety: "seguro" },
  { id: "ing-calabaza", name: "Calabaza", category: "vegetal", safety: "seguro" },
  { id: "ing-camote", name: "Camote", category: "vegetal", safety: "seguro" },
  { id: "ing-ejote", name: "Ejotes", category: "vegetal", safety: "seguro" },
  { id: "ing-espinaca", name: "Espinaca", category: "vegetal", safety: "moderacion", note: "En cantidades pequeñas" },
  { id: "ing-platano", name: "Plátano", category: "fruta", safety: "moderacion", note: "Alto en azúcar natural" },
  { id: "ing-manzana", name: "Manzana", category: "fruta", safety: "seguro", note: "Sin semillas" },
  { id: "ing-arandano", name: "Arándanos", category: "fruta", safety: "seguro" },
  { id: "ing-yogur", name: "Yogur natural", category: "grasa", safety: "moderacion", note: "Sin azúcar ni edulcorantes" },
  { id: "ing-aceite", name: "Aceite de oliva", category: "grasa", safety: "seguro" },
  { id: "ing-chia", name: "Semillas de chía", category: "suplemento", safety: "seguro" },
  { id: "ing-uva", name: "Uva", category: "fruta", safety: "evitar", note: "No apta para perros" },
  { id: "ing-cebolla", name: "Cebolla", category: "vegetal", safety: "evitar", note: "No apta para perros" },
  { id: "ing-chocolate", name: "Chocolate", category: "suplemento", safety: "evitar", note: "No apto para perros" },
];

export const RECIPES: Recipe[] = [
  {
    id: "rec-pollo-arroz",
    slug: "pollo-arroz-zanahoria",
    title: "Pollo con arroz y zanahoria",
    imageUrl: "/images/recipes/pollo-arroz.jpg",
    category: "principal",
    minutes: 20,
    servings: 2,
    needsOven: false,
    benefit: "Comida suave y equilibrada, ideal para el día a día.",
    storage: "Refrigerar hasta 3 días en recipiente hermético.",
    steps: [
      "Cocina el pollo en agua sin sal hasta que esté completamente cocido.",
      "Cocina el arroz por separado y deja enfriar.",
      "Hierve la zanahoria en cubos hasta que esté suave.",
      "Desmenuza el pollo y mezcla todo con un chorrito de aceite de oliva.",
      "Sirve a temperatura ambiente.",
    ],
    ingredients: [
      { ingredientId: "ing-pollo", name: "Pollo", quantity: 200, unit: "g" },
      { ingredientId: "ing-arroz", name: "Arroz", quantity: 100, unit: "g" },
      { ingredientId: "ing-zanahoria", name: "Zanahoria", quantity: 1, unit: "pza" },
      { ingredientId: "ing-aceite", name: "Aceite de oliva", quantity: 1, unit: "cda" },
    ],
    published: true,
    views: 1240,
  },
  {
    id: "rec-galletas-avena",
    slug: "galletas-avena-calabaza",
    title: "Galletas de avena y calabaza",
    imageUrl: "/images/recipes/galletas-avena.jpg",
    category: "premio",
    minutes: 30,
    servings: 12,
    needsOven: true,
    benefit: "Premios caseros con fibra, perfectos para el entrenamiento.",
    storage: "Frasco hermético hasta 7 días.",
    steps: [
      "Precalienta el horno a 180 °C.",
      "Mezcla la avena con el puré de calabaza y el huevo.",
      "Forma bolitas y aplánalas sobre una bandeja con papel para hornear.",
      "Hornea 20 minutos y deja enfriar completamente antes de servir.",
    ],
    ingredients: [
      { ingredientId: "ing-avena", name: "Avena", quantity: 150, unit: "g" },
      { ingredientId: "ing-calabaza", name: "Calabaza", quantity: 120, unit: "g" },
      { ingredientId: "ing-huevo", name: "Huevo", quantity: 1, unit: "pza" },
    ],
    published: true,
    views: 980,
  },
  {
    id: "rec-salmon-camote",
    slug: "salmon-con-camote",
    title: "Salmón con camote y ejotes",
    imageUrl: "/images/recipes/salmon-camote.jpg",
    category: "principal",
    minutes: 25,
    servings: 2,
    needsOven: false,
    benefit: "Aporta grasas buenas y un sabor que encanta.",
    storage: "Refrigerar hasta 2 días.",
    steps: [
      "Cuece el salmón al vapor sin condimentos y retira todas las espinas.",
      "Cocina el camote hasta que esté suave y haz un puré.",
      "Cuece los ejotes y córtalos en trozos pequeños.",
      "Mezcla y sirve tibio.",
    ],
    ingredients: [
      { ingredientId: "ing-salmon", name: "Salmón", quantity: 180, unit: "g" },
      { ingredientId: "ing-camote", name: "Camote", quantity: 150, unit: "g" },
      { ingredientId: "ing-ejote", name: "Ejotes", quantity: 80, unit: "g" },
    ],
    published: true,
    views: 764,
  },
  {
    id: "rec-helado-platano",
    slug: "helado-de-platano",
    title: "Helado de plátano y yogur",
    imageUrl: "/images/recipes/helado-platano.jpg",
    category: "snack",
    minutes: 5,
    servings: 6,
    needsOven: false,
    benefit: "Refrescante para los días calurosos.",
    storage: "Congelador hasta 30 días.",
    steps: [
      "Machaca el plátano hasta obtener un puré.",
      "Mezcla con el yogur natural sin azúcar.",
      "Vierte en moldes de silicona y congela 4 horas.",
    ],
    ingredients: [
      { ingredientId: "ing-platano", name: "Plátano", quantity: 1, unit: "pza" },
      { ingredientId: "ing-yogur", name: "Yogur natural", quantity: 150, unit: "g" },
    ],
    published: true,
    views: 1502,
  },
  {
    id: "rec-avena-manzana",
    slug: "avena-con-manzana",
    title: "Avena tibia con manzana",
    imageUrl: "/images/recipes/galletas-avena.jpg",
    category: "desayuno",
    minutes: 10,
    servings: 2,
    needsOven: false,
    benefit: "Desayuno ligero y fácil de digerir.",
    storage: "Refrigerar hasta 2 días.",
    steps: [
      "Cocina la avena en agua hasta que espese.",
      "Ralla la manzana sin semillas y agrégala.",
      "Deja enfriar antes de servir.",
    ],
    ingredients: [
      { ingredientId: "ing-avena", name: "Avena", quantity: 80, unit: "g" },
      { ingredientId: "ing-manzana", name: "Manzana", quantity: 1, unit: "pza" },
      { ingredientId: "ing-chia", name: "Semillas de chía", quantity: 1, unit: "cdta" },
    ],
    published: true,
    views: 431,
  },
  {
    id: "rec-pavo-calabaza",
    slug: "pavo-con-calabaza",
    title: "Pavo con calabaza y arroz",
    imageUrl: "/images/recipes/pollo-arroz.jpg",
    category: "principal",
    minutes: 20,
    servings: 3,
    needsOven: false,
    benefit: "Proteína magra con vegetales suaves.",
    storage: "Refrigerar hasta 3 días.",
    steps: [
      "Cocina el pavo molido en una sartén sin aceite ni sal.",
      "Cuece la calabaza y el arroz por separado.",
      "Mezcla todo y sirve tibio.",
    ],
    ingredients: [
      { ingredientId: "ing-pavo", name: "Pavo", quantity: 220, unit: "g" },
      { ingredientId: "ing-calabaza", name: "Calabaza", quantity: 120, unit: "g" },
      { ingredientId: "ing-arroz", name: "Arroz", quantity: 90, unit: "g" },
    ],
    published: true,
    views: 655,
  },
  {
    id: "rec-bocados-arandano",
    slug: "bocados-de-arandano",
    title: "Bocados de arándano y avena",
    imageUrl: "/images/recipes/helado-platano.jpg",
    category: "premio",
    minutes: 10,
    servings: 10,
    needsOven: false,
    benefit: "Premios pequeños con antioxidantes naturales.",
    storage: "Refrigerar hasta 5 días.",
    steps: [
      "Tritura los arándanos con la avena.",
      "Forma bolitas pequeñas con las manos.",
      "Refrigera 1 hora antes de servir.",
    ],
    ingredients: [
      { ingredientId: "ing-arandano", name: "Arándanos", quantity: 80, unit: "g" },
      { ingredientId: "ing-avena", name: "Avena", quantity: 100, unit: "g" },
    ],
    published: true,
    views: 288,
  },
  {
    id: "rec-caldo-hidratante",
    slug: "caldo-hidratante",
    title: "Caldo hidratante de pollo",
    imageUrl: "/images/recipes/salmon-camote.jpg",
    category: "hidratacion",
    minutes: 20,
    servings: 4,
    needsOven: false,
    benefit: "Ayuda a que tome más líquidos en días de calor.",
    storage: "Refrigerar hasta 3 días o congelar en cubos.",
    steps: [
      "Hierve el pollo en agua sin sal ni condimentos durante 20 minutos.",
      "Cuela el caldo y deja enfriar completamente.",
      "Sirve solo o mezclado con su comida.",
    ],
    ingredients: [
      { ingredientId: "ing-pollo", name: "Pollo", quantity: 150, unit: "g" },
      { ingredientId: "ing-zanahoria", name: "Zanahoria", quantity: 1, unit: "pza" },
    ],
    published: false,
    views: 96,
  },
];

export const CATEGORY_LABEL: Record<string, string> = {
  desayuno: "Desayuno",
  principal: "Plato principal",
  snack: "Snack",
  premio: "Premio",
  hidratacion: "Hidratación",
};

export const DIETARY_DISCLAIMER =
  "La información de ARIMUNDO MASCOTAS es orientativa y no reemplaza el consejo de un veterinario. Consulta siempre con un profesional antes de cambiar la alimentación de tu perro.";
