/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChefRouteImport } from './routes/chef'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanSemanalRouteImport } from './routes/plan-semanal'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRecuperarRouteImport } from './routes/auth.recuperar'
import { Route as OnboardingPerroRouteImport } from './routes/onboarding.perro'
import { Route as PerrosIndexRouteImport } from './routes/perros.index'
import { Route as PerrosDogIdRouteImport } from './routes/perros.$dogId'
import { Route as RecetasIndexRouteImport } from './routes/recetas.index'
import { Route as RecetasSlugRouteImport } from './routes/recetas.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefRoute = ChefRouteImport.update({
  id: '/chef',
  path: '/chef',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanSemanalRoute = PlanSemanalRouteImport.update({
  id: '/plan-semanal',
  path: '/plan-semanal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecuperarRoute = AuthRecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => AuthRoute,
} as any)
const OnboardingPerroRoute = OnboardingPerroRouteImport.update({
  id: '/onboarding/perro',
  path: '/onboarding/perro',
  getParentRoute: () => rootRouteImport,
} as any)
const PerrosIndexRoute = PerrosIndexRouteImport.update({
  id: '/perros/',
  path: '/perros/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerrosDogIdRoute = PerrosDogIdRouteImport.update({
  id: '/perros/$dogId',
  path: '/perros/$dogId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetasIndexRoute = RecetasIndexRouteImport.update({
  id: '/recetas/',
  path: '/recetas/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetasSlugRoute = RecetasSlugRouteImport.update({
  id: '/recetas/$slug',
  path: '/recetas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/chef': typeof ChefRoute
  '/compras': typeof ComprasRoute
  '/perfil': typeof PerfilRoute
  '/plan-semanal': typeof PlanSemanalRoute
  '/planes': typeof PlanesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/onboarding/perro': typeof OnboardingPerroRoute
  '/perros/$dogId': typeof PerrosDogIdRoute
  '/recetas/$slug': typeof RecetasSlugRoute
  '/perros/': typeof PerrosIndexRoute
  '/recetas/': typeof RecetasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/chef': typeof ChefRoute
  '/compras': typeof ComprasRoute
  '/perfil': typeof PerfilRoute
  '/plan-semanal': typeof PlanSemanalRoute
  '/planes': typeof PlanesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/onboarding/perro': typeof OnboardingPerroRoute
  '/perros/$dogId': typeof PerrosDogIdRoute
  '/recetas/$slug': typeof RecetasSlugRoute
  '/perros': typeof PerrosIndexRoute
  '/recetas': typeof RecetasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/chef': typeof ChefRoute
  '/compras': typeof ComprasRoute
  '/perfil': typeof PerfilRoute
  '/plan-semanal': typeof PlanSemanalRoute
  '/planes': typeof PlanesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/onboarding/perro': typeof OnboardingPerroRoute
  '/perros/$dogId': typeof PerrosDogIdRoute
  '/recetas/$slug': typeof RecetasSlugRoute
  '/perros/': typeof PerrosIndexRoute
  '/recetas/': typeof RecetasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chef'
    | '/compras'
    | '/perfil'
    | '/plan-semanal'
    | '/planes'
    | '/reset-password'
    | '/auth/recuperar'
    | '/onboarding/perro'
    | '/perros/$dogId'
    | '/recetas/$slug'
    | '/perros/'
    | '/recetas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/chef'
    | '/compras'
    | '/perfil'
    | '/plan-semanal'
    | '/planes'
    | '/reset-password'
    | '/auth/recuperar'
    | '/onboarding/perro'
    | '/perros/$dogId'
    | '/recetas/$slug'
    | '/perros'
    | '/recetas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chef'
    | '/compras'
    | '/perfil'
    | '/plan-semanal'
    | '/planes'
    | '/reset-password'
    | '/auth/recuperar'
    | '/onboarding/perro'
    | '/perros/$dogId'
    | '/recetas/$slug'
    | '/perros/'
    | '/recetas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRouteWithChildren
  ChefRoute: typeof ChefRoute
  ComprasRoute: typeof ComprasRoute
  PerfilRoute: typeof PerfilRoute
  PlanSemanalRoute: typeof PlanSemanalRoute
  PlanesRoute: typeof PlanesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  OnboardingPerroRoute: typeof OnboardingPerroRoute
  PerrosDogIdRoute: typeof PerrosDogIdRoute
  RecetasSlugRoute: typeof RecetasSlugRoute
  PerrosIndexRoute: typeof PerrosIndexRoute
  RecetasIndexRoute: typeof RecetasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef': {
      id: '/chef'
      path: '/chef'
      fullPath: '/chef'
      preLoaderRoute: typeof ChefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-semanal': {
      id: '/plan-semanal'
      path: '/plan-semanal'
      fullPath: '/plan-semanal'
      preLoaderRoute: typeof PlanSemanalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recuperar': {
      id: '/auth/recuperar'
      path: '/recuperar'
      fullPath: '/auth/recuperar'
      preLoaderRoute: typeof AuthRecuperarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/onboarding/perro': {
      id: '/onboarding/perro'
      path: '/onboarding/perro'
      fullPath: '/onboarding/perro'
      preLoaderRoute: typeof OnboardingPerroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perros/': {
      id: '/perros/'
      path: '/perros'
      fullPath: '/perros/'
      preLoaderRoute: typeof PerrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perros/$dogId': {
      id: '/perros/$dogId'
      path: '/perros/$dogId'
      fullPath: '/perros/$dogId'
      preLoaderRoute: typeof PerrosDogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas/': {
      id: '/recetas/'
      path: '/recetas'
      fullPath: '/recetas/'
      preLoaderRoute: typeof RecetasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas/$slug': {
      id: '/recetas/$slug'
      path: '/recetas/$slug'
      fullPath: '/recetas/$slug'
      preLoaderRoute: typeof RecetasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthRecuperarRoute: typeof AuthRecuperarRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRecuperarRoute: AuthRecuperarRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRouteWithChildren,
  ChefRoute: ChefRoute,
  ComprasRoute: ComprasRoute,
  PerfilRoute: PerfilRoute,
  PlanSemanalRoute: PlanSemanalRoute,
  PlanesRoute: PlanesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  OnboardingPerroRoute: OnboardingPerroRoute,
  PerrosDogIdRoute: PerrosDogIdRoute,
  RecetasSlugRoute: RecetasSlugRoute,
  PerrosIndexRoute: PerrosIndexRoute,
  RecetasIndexRoute: RecetasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
